cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "beeftornado/rmtree"

brew "mackup"
brew "mas"
brew "youtube-dl"

cask "alfred"
# cask "background-music"
cask "dropbox"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "google-chrome"
cask "mounty"
cask "spotify"
cask "stretchly"
cask "the-unarchiver"
cask "tomighty"
cask "transmission"
cask "tripmode"
cask "vlc"
cask "whatsapp"

mas "Noizio", id: 928871589
mas "Things", id: 904280696
mas "Tim", id: 1449619230
mas "Wipr", id: 1320666476
mas "NordVPN IKE", id: 1116599239
mas "Instapaper", id: 1481302432
